module.exports = {
  rndText_learnFrom: [
    "gallery",
    "joint",
    "litigation",
    "knot",
    "pardon",
    "crew",
    "provide",
    "trance",
    "sample",
    "particular",
    "combine",
    "overall",
    "torch",
    "positive",
    "cabinet",
    "favourite",
    "disagree",
    "building",
    "direction",
    "present",
    "contraction",
    "thinker",
    "liability",
    "my",
    "sweater",
    "harvest",
    "urgency",
    "output",
    "compose",
    "withdraw",
    "ambition",
    "difference",
    "bubble",
    "colony",
    "man",
    "literature",
    "crackpot",
    "guitar",
    "rich",
    "occasion",
    "Dollie Carlson",
    "Dong Zhang",
    "Noah Kramer",
    "Jerrold Norton",
    "Bridgett Crawford",
    "Connie Moses",
    "Wilton Wall",
    "Rosario Norman",
    "Cary Novak",
    "Lewis Contreras",
    "Amelia Anthony",
    "Myra Castaneda",
    "Charles Molina",
    "Cheri Whitaker",
    "Hilda Parrish",
    "Elroy Luna",
    "Brooks Roberts",
    "Antonia Bush",
    "Monroe Bell",
    "Huey Davidson",
    "Antone Potts",
    "Patsy Faulkner",
    "Luann Weber",
    "Tania Terry",
    "Minh Owen",
    "Curtis Hester",
    "Judith Flores",
    "Pearl Braun",
    "Mckinley Elliott",
    "Blair Sheppard",
    "Alfreda Zuniga",
    "Leopoldo Randolph",
    "Susanna Mcbride",
    "Nickolas Allen",
    "Houston Jones",
    "Abram Davila",
    "Ty Hinton",
    "Janis Meyers",
    "Irwin Crane",
    "Jere Rosales",
    "He barked orders at his daughters but they just stared back with amusement.",
    "She did a happy dance because all of the socks from the dryer matched.",
    "She works two jobs to make ends meet; at least, that was her reason for not having time to join us.",
    "They ran around the corner to find that they had traveled back in time.",
    "It isn't difficult to do a handstand if you just stand on your hands.",
    "The light in his life was actually a fire burning all around him.",
    "Andy loved to sleep on a bed of nails.",
    "The snow-covered path was no help in finding his way out of the back-country.",
    "I don’t respect anybody who can’t tell the difference between Pepsi and Coke.",
    "The bullet pierced the window shattering it before missing Danny's head by mere millimeters.",
    "The father died during childbirth.",
    "The pet shop stocks everything you need to keep your anaconda happy.",
    "Although it wasn't a pot of gold, Nancy was still enthralled at what she found at the end of the rainbow.",
    "The underground bunker was filled with chips and candy.",
    "Jason lived his life by the motto, &quot;Anything worth doing is worth doing poorly.",
    "She was amazed by the large chunks of ice washing up on the beach.",
    "The elephant didn't want to talk about the person in the room.",
    "Today arrived with a crash of my car through the garage door.",
    "Nobody questions who built the pyramids in Mexico.",
    "The near-death experience brought new ideas to light.",
  ],
  rndTextNoSpace_learnFrom: [
    "gallery",
    "joint",
    "litigation",
    "knot",
    "pardon",
    "crew",
    "provide",
    "trance",
    "sample",
    "particular",
    "combine",
    "overall",
    "torch",
    "positive",
    "cabinet",
    "favourite",
    "disagree",
    "building",
    "direction",
    "present",
    "contraction",
    "thinker",
    "liability",
    "my",
    "sweater",
    "harvest",
    "urgency",
    "output",
    "compose",
    "withdraw",
    "ambition",
    "difference",
    "bubble",
    "colony",
    "man",
    "literature",
    "crackpot",
    "guitar",
    "rich",
    "occasion",
  ],
  rndTextEncrypted_learnFrom: [
    "eRSpzhEBbzOWMPgQJlOSye45XKa9ITM0",
    "IZMHntdBEy5PEqH2T7U2R/9n4mV8KfMr",
    "JWz5lp0cICExMiH1+92NBual41n+S0Mf",
    "rOut7XV0ujfMITExIaPS7NL8QpEC3mW7",
    "GFUXEA+dR7fPzyExMCGHF+OkDvtBZWhb",
    "zExWOSE5ISEzNCHSBGLMHIYgBtvGITAh",
    "cF0j1uNIaq4wwEyq96PR5RjkYW8I2nTh",
    "y9d9qH6wzLchMzkhZigyGcp6XOvFwuCo",
    "0LxHOO89geR8ZAfG2RCBSkeBHXikwQgc",
    "D+khMzQhb87CITEyIcflEuUhMTMhMyEx",
    "RbI8YLiSTEiuriEzOSGbhnhpCL9/ZxkU",
    "ZiEzOSEhMTEhITE2MCEEUyqNJenA5nOf",
    "6K4hMzMhjNIhMzMhOdSPuFdbyQP45qhk",
    "qY+f0ehkfzzkSn0SuqHMz1jjgD0towOR",
    "9X9N//0R9RvexUjnR8lpVLs88yEzOSFy",
    "wVeYXh5R9jmybCP/5KT0BoGtaT07a4U5",
    "M/Ytqb+1vUDXsKXg6CiH6OSul+A7HYTT",
    "NlaDzrlb6DqPTZPnTIKPqh59BinbMY3J",
    "vbBxgCQx7wg8Wpvi8CExNjAhuGcgrt1C",
    "5lb09H99AvkZ4da3jAbMITEzIV8dY+Q1",
    "v34xmyEzMyEtD6shMzkh14f4V4rXhYU/",
    "MTMhTDXaNhFEcHiPU4A6sIUcITAhu3Ho",
    "5Xlfx8QhMTMhLJ/4nakhMTEh0A/Og3wt",
    "MUwhMTEhjCExNjAhL9XSGlMDLd9GufOf",
    "+pweUOTVHzlaVhbmD0bbSgiLCBbmGr1U",
    "VVGNBgUCwQOV5k2+ziExMSHhf+7wst96",
    "ulVpw0ldjK/Q7TrsVhWZp32E/846JomX",
    "45cDhyEwIcH4OMqRITM5IWe/UEE9927N",
    "aZP2/iVVVBmOhEqNrucDPJav4bh/uEpS",
    "IIPgITEyIRSt0imYGTRyPeGY8FU+uwGd",
    "/CExMyG2ZSExNjAhZMxyS13xpAUXyMzy",
    "KbpmYaVJLJ8kz0oCEFcchc95+5LlxtR3",
    "X7PQX5xr6oG5B12/RVaLHkRJc3emfCaF",
    "XoIyGrm8Ldr4V4rXhYU/SCExMiGOaKdl",
    "abSLestHGYbBhOlPZSExMiFTpzst8VCe",
    "F54C6pyoCBbmGr1UUkVOqOfzZPfQWnrQ",
    "bv3JAY8hMCGPn9HoZH885Ep9ErqhzM9Y",
    "zsD7ITMzIYbBLY3BAZTk+OaHBe+uLwSB",
    "pfaxafOHxIbpsWww7kg67+hZcXW7/NRD",
    "s0UQEujV9fZY15rtZfrsu+o51yEzMyEw",
    "Sf7jz4Y2kr72Q6b8JIJD4HTYITExIXNV",
    "y1xLITEzIRXpFfw65yE5IUUH0xFExW7N",
    "aZP2/iVV4My+LvMhMTAh0gQWwqPP7pLO",
    "ITkhpdnBKSEzMyFlxsJanyvrP8chMTIh",
    "M9f88+ZhJnredndjVm+usvkjGx9lA2d7",
    "ILbp0kOTf4s6Mt6L3DUoja2EOE4vvj+Z",
    "lRw0+okYSY/Uum6kxBbr4s5xy0FI+PfP",
    "Zpbi2E6SusbAMyEwIcGEDqj/KWuNYxv9",
    "Y01D38c1/CsBpZCtk4ezkH+Csnzpi152",
    "eZDUITEyIcflEuUhMTMhMyExMSEe8jRm",
    "ITMzIfcunbnnDqiJQli4dVN8DmtlkF1U",
    "7IjV5Zd4/mhWtAKbwezlEKHfyxwopH40",
    "0sLYmrvoz7mSsLYuhO1p/omqad0oWR4h",
    "MCGqITEzIUzEhhL8XY4DiCDHO/fBghNA",
    "brl8s4kClxbRGonaM1gea+hV4EIDjIDr",
  ],
  rndTextCRC_learnFrom: [
    "0011110110000101001",
    "11",
    "001110110011110101",
    "0",
    "1101011100110",
    "1",
    "0001101111010111011",
    "11001",
    "1",
    "01100001001101011",
    "111",
    "1110001000010101011",
    "010111100001",
    "11010001011",
    "01100",
    "0",
    "10",
    "0100",
    "011101",
    "0010010010101011",
    "001111100100",
    "00010100011000110011",
    "1111",
    "0011001",
    "11111111",
    "010100",
    "10101000010",
    "01",
    "1100110101010",
    "01100000111011111001",
  ],
};
